# Generated by Django 6.0.2 on 2026-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantities',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
